/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.ItemDao;
import dao.TransactionDao;
import dao.UserDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Item;
import model.ItemType;
import model.Language;
import model.LibraryMember;
import model.RentType;
import model.Transaction;
import model.TransactionType;
import model.User;
import service.InventoryService;
import service.ItemService;
import service.TransactionService;
import service.UserService;

/**
 *
 * @author kailainathan
 */
public class LibraryForm extends javax.swing.JFrame {
    
    // declare services
    public final ItemService itemService;
    public final UserService userService;
    private final InventoryService inventoryService;
    private final TransactionService transactionService;


    /**
     * Creates new form LibraryForm
     */
    public LibraryForm() {
        initComponents();
        closeAllWindows();
        
        // create service objects
        ItemDao itemDao = new ItemDao();
        itemService = new ItemService(itemDao);
        userService = new UserService(new UserDao());
        inventoryService = new InventoryService(itemDao);
        transactionService = new TransactionService(new TransactionDao());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        addItemWindow = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        addItemBtn = new javax.swing.JButton();
        title = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        publishedDate = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        language = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        publisher = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        isbn = new javax.swing.JTextField();
        noOfCopiesToBorrow = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        itemType = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        findMemberWindow = new javax.swing.JInternalFrame();
        jLabel17 = new javax.swing.JLabel();
        selectMemberBy = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        txtFindMember = new javax.swing.JTextField();
        findItemWindow = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        findByVal = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtPublisher = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        cbType = new javax.swing.JComboBox<>();
        cbLan = new javax.swing.JComboBox<>();
        txtAvailable = new javax.swing.JTextField();
        txtCurrent = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtDate = new javax.swing.JTextField();
        lFindBy = new javax.swing.JLabel();
        findByType = new javax.swing.JComboBox<>();
        jTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        inventoryReportWindow = new javax.swing.JInternalFrame();
        button1 = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        cbReportType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        addItem = new javax.swing.JMenuItem();
        findItem = new javax.swing.JMenuItem();
        findMember = new javax.swing.JMenuItem();
        inventoryReport = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Window");
        setBackground(new java.awt.Color(153, 153, 153));

        addItemWindow.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        addItemWindow.setClosable(true);
        addItemWindow.setMaximizable(true);
        addItemWindow.setResizable(true);
        addItemWindow.setTitle("Add Item");
        addItemWindow.setVisible(true);

        jLabel1.setText("Title");

        addItemBtn.setText("Add Item");
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Code");

        jLabel13.setText("Author");

        jLabel14.setText("Published Date");

        jLabel15.setText("Type");

        type.setModel(new DefaultComboBoxModel(RentType.values()));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        jLabel16.setText("Language");

        language.setModel(new DefaultComboBoxModel(Language.values()));

        jLabel18.setText("Publisher");

        jLabel19.setText("ISBN");

        jLabel20.setText("No of copies available to borrow");

        jLabel21.setText("Item Type");

        itemType.setModel(new DefaultComboBoxModel(ItemType.values()));

        javax.swing.GroupLayout addItemWindowLayout = new javax.swing.GroupLayout(addItemWindow.getContentPane());
        addItemWindow.getContentPane().setLayout(addItemWindowLayout);
        addItemWindowLayout.setHorizontalGroup(
            addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemWindowLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(4, 4, Short.MAX_VALUE)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addItemBtn)
                    .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(isbn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addComponent(publishedDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(itemType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noOfCopiesToBorrow, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(publisher, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(language, javax.swing.GroupLayout.Alignment.LEADING, 0, 72, Short.MAX_VALUE)
                        .addComponent(type, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(author, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(code, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(title, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        addItemWindowLayout.setVerticalGroup(
            addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemWindowLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(publishedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noOfCopiesToBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(31, 31, 31)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(9, 9, 9)
                .addGroup(addItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addComponent(addItemBtn)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        findMemberWindow.setVisible(true);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Find member"), findMemberWindow, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        jLabel17.setText("Find By");

        selectMemberBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Type" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member Name", "Address", "Type", "Contact No", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton3.setText("Find");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtFindMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout findMemberWindowLayout = new javax.swing.GroupLayout(findMemberWindow.getContentPane());
        findMemberWindow.getContentPane().setLayout(findMemberWindowLayout);
        findMemberWindowLayout.setHorizontalGroup(
            findMemberWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findMemberWindowLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(findMemberWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(findMemberWindowLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(75, 75, 75)
                        .addComponent(selectMemberBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtFindMember, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addGap(70, 70, 70))
        );
        findMemberWindowLayout.setVerticalGroup(
            findMemberWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findMemberWindowLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(findMemberWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(selectMemberBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFindMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        findItemWindow.setClosable(true);
        findItemWindow.setMaximizable(true);
        findItemWindow.setResizable(true);
        findItemWindow.setTitle("Find Item");
        findItemWindow.setAutoscrolls(true);
        findItemWindow.setVisible(true);

        jLabel4.setText("Author");

        jLabel5.setText("Published Date");

        jLabel6.setText("ISBN");

        jLabel7.setText("Publisher");

        jLabel9.setText("No of copies available to borrow");

        jLabel10.setText("No of copies currently borrowed");

        jLabel11.setText("Language");

        findByVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findByValActionPerformed(evt);
            }
        });

        txtAuthor.setEditable(false);
        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });

        txtPublisher.setEditable(false);
        txtPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPublisherActionPerformed(evt);
            }
        });

        txtIsbn.setEditable(false);
        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });

        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BORROW", "REFERENCE", " " }));
        cbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeActionPerformed(evt);
            }
        });

        cbLan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENGLISH", "SINHALA", "TAMIL" }));
        cbLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLanActionPerformed(evt);
            }
        });

        txtAvailable.setEditable(false);
        txtAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailableActionPerformed(evt);
            }
        });

        txtCurrent.setEditable(false);
        txtCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentActionPerformed(evt);
            }
        });

        jLabel8.setText("Type");

        jButton2.setLabel("Find Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtDate.setEditable(false);
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        lFindBy.setText("Find By");

        findByType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "ID" }));
        findByType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findByTypeActionPerformed(evt);
            }
        });

        jTitle.setText("Title");

        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout findItemWindowLayout = new javax.swing.GroupLayout(findItemWindow.getContentPane());
        findItemWindow.getContentPane().setLayout(findItemWindowLayout);
        findItemWindowLayout.setHorizontalGroup(
            findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findItemWindowLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findItemWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(findItemWindowLayout.createSequentialGroup()
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel7))
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel10))
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel11))
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel8))
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel9))
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel5))
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lFindBy)
                        .addGap(65, 65, 65)
                        .addComponent(findByType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findItemWindowLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(findByVal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(txtTitle)
                            .addComponent(cbLan, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCurrent)
                            .addComponent(txtAvailable)
                            .addComponent(cbType, 0, 86, Short.MAX_VALUE)
                            .addComponent(txtPublisher)
                            .addComponent(txtIsbn)
                            .addComponent(txtAuthor)
                            .addComponent(txtDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton2)
                .addGap(41, 41, 41))
        );
        findItemWindowLayout.setVerticalGroup(
            findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findItemWindowLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(findByVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFindBy)
                    .addComponent(findByType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4)))
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5))
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbLan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jButton2.getAccessibleContext().setAccessibleName("find");

        inventoryReportWindow.setMaximizable(true);
        inventoryReportWindow.setResizable(true);
        inventoryReportWindow.setTitle("Inventory Report");
        inventoryReportWindow.setVisible(true);

        button1.setLabel("Report");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(reportTable);

        cbReportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inventory", "Finance", "Transaction" }));

        jLabel3.setText("Report Type");

        javax.swing.GroupLayout inventoryReportWindowLayout = new javax.swing.GroupLayout(inventoryReportWindow.getContentPane());
        inventoryReportWindow.getContentPane().setLayout(inventoryReportWindowLayout);
        inventoryReportWindowLayout.setHorizontalGroup(
            inventoryReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryReportWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbReportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryReportWindowLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        inventoryReportWindowLayout.setVerticalGroup(
            inventoryReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryReportWindowLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(inventoryReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inventoryReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbReportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );

        jMenu3.setText("File");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        addItem.setLabel("Add Item");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });
        jMenu3.add(addItem);

        findItem.setText("Find Item");
        findItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findItemActionPerformed(evt);
            }
        });
        jMenu3.add(findItem);

        findMember.setText("Find Member");
        findMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findMemberActionPerformed(evt);
            }
        });
        jMenu3.add(findMember);

        inventoryReport.setText("Inventory Report");
        inventoryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryReportActionPerformed(evt);
            }
        });
        jMenu3.add(inventoryReport);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1756, 1756, 1756))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addItemWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(inventoryReportWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(findItemWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(findMemberWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1555, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(addItemWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inventoryReportWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(174, 174, 174)
                .addComponent(findItemWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208)
                .addComponent(findMemberWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3749, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
       closeAllWindows();
      addItemWindow.setVisible(true);
              
    }//GEN-LAST:event_addItemActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void findItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findItemActionPerformed
        // TODO add your handling code here:
        closeAllWindows();
        findItemWindow.setVisible(true);
    }//GEN-LAST:event_findItemActionPerformed

    private void cbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTypeActionPerformed

    private void findByValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findByValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findByValActionPerformed

    private void findMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findMemberActionPerformed
        closeAllWindows();
        findMemberWindow.setVisible(true);
    }//GEN-LAST:event_findMemberActionPerformed

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed

        // creating an object for item  
        Item item = new Item();        
        item.setTitle(title.getText());
        item.setCode(code.getText());
        item.setAuthor(author.getText());
        item.setPublisher(publisher.getText());
        item.setPublishedDate(((JTextField) publishedDate.getDateEditor().getUiComponent()).getText());
        item.setIsbn(isbn.getText());
        item.setNoOfCopiesToBorrow(Integer.parseInt(noOfCopiesToBorrow.getText()));
        item.setRentType((RentType)type.getSelectedItem());
        item.setLanguage((Language)language.getSelectedItem());
        item.setItemType((ItemType)(itemType.getSelectedItem()));
        itemService.addItem(item);
        transactionService.addTransaction(new Transaction(TransactionType.ADD));
    }//GEN-LAST:event_addItemBtnActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void findByTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findByTypeActionPerformed
        
    }//GEN-LAST:event_findByTypeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //get the value from the select box 
        String selectedFindByType = String.valueOf(findByType.getSelectedItem());
        
        
        //get the value from the textbox 
        String selectedValue = findByVal.getText();
        
        if(selectedFindByType == "Title") {
        //get item by title
          Item item =  itemService.findItemByTitle(selectedValue);
          txtAuthor.setText(item.getAuthor());
          txtPublisher.setText(item.getPublisher());
          txtTitle.setText(item.getTitle());
          txtId.setText(item.getCode());
          txtIsbn.setText(item.getIsbn());
          txtDate.setText(item.getPublishedDate());
          txtAvailable.setText(Integer.toString(item.getNoOfCopiesToBorrow()));
          txtCurrent.setText(Integer.toString(item.getNoOfCopiesCurrentlyBorrowed()));
          cbType.setSelectedItem(item.getRentType().toString());
          cbLan.setSelectedItem(item.getLanguage().toString());  
        } 
        else {
          Item item =  itemService.findItemById(selectedValue);
          txtAuthor.setText(item.getAuthor());
          txtPublisher.setText(item.getPublisher());
          txtTitle.setText(item.getTitle());
          txtId.setText(item.getCode());
          txtIsbn.setText(item.getIsbn());
          txtDate.setText(item.getPublishedDate());
          txtAvailable.setText(Integer.toString(item.getNoOfCopiesToBorrow()));
          txtCurrent.setText(Integer.toString(item.getNoOfCopiesCurrentlyBorrowed()));
          cbType.setSelectedItem(item.getRentType().toString());
          cbLan.setSelectedItem(item.getLanguage().toString());         
        }
        transactionService.addTransaction(new Transaction(TransactionType.FIND));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String selectedSelectMemberBy = String.valueOf(selectMemberBy.getSelectedItem());
       
       //get the value from the text box 
       String selectedValue = txtFindMember.getText();
       
       // if combobox selected value is id 
       if(selectedSelectMemberBy == "Id"){
           //creating a array list of  LibraryMember
            ArrayList<LibraryMember> list = new ArrayList<LibraryMember>();
             // getting the librarymember and adding it to the list 
             LibraryMember member = userService.findById(selectedValue);
             
             if(member != null) {
                    list.add(member);
             addToTable(list);
             } else {
                //display message member not found
             }
           
       } else {
           addToTable(userService.findByType(selectedValue));
           
       }
       
       transactionService.addTransaction(new Transaction(TransactionType.FIND));
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    private void addToTable(ArrayList<LibraryMember> list) {
            DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            //creating an array of 5 ( for table rows)
            Object rowData[] = new Object[5];
            
            //loop through the list addig it to the table 
            for(int i = 0; i < list.size(); i++)
            {
                rowData[0] = list.get(i).getName();
                rowData[1] = list.get(i).getAddress();
                rowData[2] = list.get(i).getMemberType();
                rowData[3] = list.get(i).getContactNo();
                rowData[4] = list.get(i).getMemberStatus();
                model.addRow(rowData);
                 
            }
    }
    
    private void txtFindMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindMemberActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void txtPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPublisherActionPerformed

    private void txtAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailableActionPerformed

    private void txtCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentActionPerformed

    private void cbLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLanActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        String selectedReportType = cbReportType.getSelectedItem().toString();
        if(selectedReportType == "Inventory") {
            addInventoryReportTable(inventoryService.getInventoryReport());
        } else if (selectedReportType == "Transaction") {
            addTransactionReportTable(transactionService.getAllTransaction());
        }
        
        transactionService.addTransaction(new Transaction(TransactionType.REPORT));
        
    }//GEN-LAST:event_button1ActionPerformed

    private void inventoryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryReportActionPerformed
        closeAllWindows();
        inventoryReportWindow.setVisible(true);
    }//GEN-LAST:event_inventoryReportActionPerformed

    
    private void addInventoryReportTable(ArrayList<Item> itemList) {
        String[] columnNames = {"Item Code",
                        "Title",
                        "No of Copies avaliable"
                       };
        
         DefaultTableModel model =  (DefaultTableModel) reportTable.getModel();
            model.setRowCount(0);
            model.setColumnCount(3);
    reportTable.getColumnModel().getColumn(0).setHeaderValue("Item Code");
    reportTable.getColumnModel().getColumn(1).setHeaderValue("Title");
    reportTable.getColumnModel().getColumn(2).setHeaderValue("Avilable copies");
    reportTable.getTableHeader().resizeAndRepaint();
            Object rowData[] = new Object[3];
                        for(int i = 0; i < itemList.size(); i++)
            {
                rowData[0] = itemList.get(i).getCode();
                rowData[1] = itemList.get(i).getTitle();
                rowData[2] = itemList.get(i).getNoOfCopiesToBorrow();
                model.addRow(rowData);
                 
            }
    }
    
    private void addTransactionReportTable(ArrayList<Transaction> itemList) {
          DefaultTableModel model =  (DefaultTableModel) reportTable.getModel();
            model.setRowCount(0);
            model.setColumnCount(2);
    reportTable.getColumnModel().getColumn(0).setHeaderValue("Transaction Type");
    reportTable.getColumnModel().getColumn(1).setHeaderValue("Date");
    reportTable.getTableHeader().resizeAndRepaint();
    
            Object rowData[] = new Object[3];
                        for(int i = 0; i < itemList.size(); i++)
            {
                rowData[0] = itemList.get(i).getTransactionType();
                rowData[1] = itemList.get(i).getLocalDate();
                model.addRow(rowData);
                 
            }
    }
    
    private void closeAllWindows(){
        findItemWindow.setVisible(false);
        addItemWindow.setVisible(false);
        findMemberWindow.setVisible(false);
        inventoryReportWindow.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addItem;
    private javax.swing.JButton addItemBtn;
    private javax.swing.JInternalFrame addItemWindow;
    private javax.swing.JTextField author;
    private java.awt.Button button1;
    private javax.swing.JComboBox<String> cbLan;
    private javax.swing.JComboBox<String> cbReportType;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JTextField code;
    private javax.swing.JComboBox<String> findByType;
    private javax.swing.JTextField findByVal;
    private javax.swing.JMenuItem findItem;
    private javax.swing.JInternalFrame findItemWindow;
    private javax.swing.JMenuItem findMember;
    private javax.swing.JInternalFrame findMemberWindow;
    private javax.swing.JMenuItem inventoryReport;
    private javax.swing.JInternalFrame inventoryReportWindow;
    private javax.swing.JTextField isbn;
    private javax.swing.JComboBox<String> itemType;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTitle;
    private javax.swing.JLabel lFindBy;
    private javax.swing.JComboBox<String> language;
    private javax.swing.JTextField noOfCopiesToBorrow;
    private com.toedter.calendar.JDateChooser publishedDate;
    private javax.swing.JTextField publisher;
    private javax.swing.JTable reportTable;
    private javax.swing.JComboBox<String> selectMemberBy;
    private javax.swing.JTextField title;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtAvailable;
    private javax.swing.JTextField txtCurrent;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFindMember;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtPublisher;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JComboBox<String> type;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
