/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.ItemTransactionDao;
import dao.ItemDao;
import dao.TransactionDao;
import dao.UserDao;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.ItemTransaction;
import model.Item;
import model.ItemType;
import model.Language;
import model.LibraryMember;
import model.RentType;
import model.Transaction;
import model.TransactionType;
import service.ItemTransactionService;
import service.ItemService;
import service.TransactionService;
import service.UserService;

/**
 *
 * @author kailainathan
 */
public class MemberForm extends javax.swing.JFrame {

    /**
     * Creates new form MemberForm
     */
    public final ItemTransactionService borrowItemService;
    public final ItemService itemService;
    private final TransactionService transactionService;
    private final UserService userService;
    
    public MemberForm() {
        borrowItemService = new ItemTransactionService(new ItemTransactionDao());
        itemService = new ItemService(new ItemDao());
        transactionService = new TransactionService(new TransactionDao());
        userService = new UserService(new UserDao());
        initComponents();
        closeAllWindows();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        returnItemWindow = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rItemCodeTxt = new javax.swing.JTextField();
        rMemberIdTxt = new javax.swing.JTextField();
        returnDateTxt = new com.toedter.calendar.JDateChooser();
        returnItemBtn = new javax.swing.JButton();
        findItemWindow = new javax.swing.JInternalFrame();
        lFindBy = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        findByVal = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtPublisher = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        cbType = new javax.swing.JComboBox<>();
        cbLan = new javax.swing.JComboBox<>();
        txtAvailable = new javax.swing.JTextField();
        txtCurrent = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtDate = new javax.swing.JTextField();
        jTitle = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        findByType = new javax.swing.JComboBox<>();
        borrowItemWindow = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        itemCodeTxt = new javax.swing.JTextField();
        memberIdTxt = new javax.swing.JTextField();
        borrowItemBtn = new javax.swing.JButton();
        borrowDateTxt = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        returnItem = new javax.swing.JMenuItem();
        borrowItem = new javax.swing.JMenuItem();
        findItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        returnItemWindow.setVisible(true);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Return Item"), returnItemWindow, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        jLabel6.setText("Item Code");

        jLabel7.setText("Member Id");

        jLabel8.setText("Returned Date");

        returnDateTxt.setDate(new Date());
        returnDateTxt.setDateFormatString("dd/MM/yyyy");

        returnItemBtn.setText("Return");
        returnItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnItemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnItemWindowLayout = new javax.swing.GroupLayout(returnItemWindow.getContentPane());
        returnItemWindow.getContentPane().setLayout(returnItemWindowLayout);
        returnItemWindowLayout.setHorizontalGroup(
            returnItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnItemWindowLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(returnItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addComponent(jLabel8))
                .addGap(71, 71, 71)
                .addGroup(returnItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(returnItemBtn)
                        .addComponent(rItemCodeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addComponent(rMemberIdTxt))
                    .addComponent(returnDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        returnItemWindowLayout.setVerticalGroup(
            returnItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnItemWindowLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(returnItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rItemCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(returnItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rMemberIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(returnItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(returnDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(returnItemBtn)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        findItemWindow.setClosable(true);
        findItemWindow.setMaximizable(true);
        findItemWindow.setResizable(true);
        findItemWindow.setTitle("Find Item");
        findItemWindow.setVisible(true);

        lFindBy.setText("Find By");

        jLabel10.setText("Author");

        jLabel11.setText("Published Dtae");

        jLabel12.setText("ISBN");

        jLabel13.setText("Publisher");

        jLabel14.setText("No of copies available to borrow");

        jLabel15.setText("No of copies currently borrowed");

        jLabel16.setText("Language");

        findByVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findByValActionPerformed(evt);
            }
        });

        txtAuthor.setEditable(false);
        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });

        txtPublisher.setEditable(false);
        txtPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPublisherActionPerformed(evt);
            }
        });

        txtIsbn.setEditable(false);
        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });

        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BORROW", "REFERENCE" }));
        cbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeActionPerformed(evt);
            }
        });

        cbLan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENGLISH", "SINHALA", "TAMIL" }));
        cbLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLanActionPerformed(evt);
            }
        });

        txtAvailable.setEditable(false);

        txtCurrent.setEditable(false);

        jLabel17.setText("Type");

        jButton2.setLabel("Find Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtDate.setEditable(false);
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        jTitle.setText("Title");

        jLabel19.setText("ID");

        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        findByType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "ID" }));

        javax.swing.GroupLayout findItemWindowLayout = new javax.swing.GroupLayout(findItemWindow.getContentPane());
        findItemWindow.getContentPane().setLayout(findItemWindowLayout);
        findItemWindowLayout.setHorizontalGroup(
            findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findItemWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(findItemWindowLayout.createSequentialGroup()
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(jLabel19)
                            .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lFindBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(findByType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(findItemWindowLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTitle)
                            .addComponent(cbLan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCurrent, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAvailable, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbType, javax.swing.GroupLayout.Alignment.LEADING, 0, 86, Short.MAX_VALUE)
                            .addComponent(txtPublisher, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAuthor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findItemWindowLayout.createSequentialGroup()
                        .addComponent(findByVal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addComponent(jButton2)
                .addGap(41, 41, 41))
        );
        findItemWindowLayout.setVerticalGroup(
            findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findItemWindowLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(findByVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFindBy)
                    .addComponent(findByType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(17, 17, 17)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(findItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbLan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        borrowItemWindow.setVisible(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Borrow Item"), borrowItemWindow, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        jLabel3.setText("Item Code");

        jLabel4.setText("Member Id");

        jLabel5.setText("Borrow Date");

        itemCodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeTxtActionPerformed(evt);
            }
        });

        borrowItemBtn.setText("Borrow");
        borrowItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowItemBtnActionPerformed(evt);
            }
        });

        borrowDateTxt.setDate(new Date());
        borrowDateTxt.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout borrowItemWindowLayout = new javax.swing.GroupLayout(borrowItemWindow.getContentPane());
        borrowItemWindow.getContentPane().setLayout(borrowItemWindowLayout);
        borrowItemWindowLayout.setHorizontalGroup(
            borrowItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowItemWindowLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(borrowItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(83, 83, 83)
                .addGroup(borrowItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrowItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(borrowItemBtn)
                        .addComponent(itemCodeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(memberIdTxt))
                    .addComponent(borrowDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        borrowItemWindowLayout.setVerticalGroup(
            borrowItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowItemWindowLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(borrowItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(memberIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowItemWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(borrowDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(borrowItemBtn)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        returnItem.setText("Return Item");
        returnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnItemActionPerformed(evt);
            }
        });
        jMenu1.add(returnItem);

        borrowItem.setText("Borrow Item");
        borrowItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowItemActionPerformed(evt);
            }
        });
        jMenu1.add(borrowItem);

        findItem.setText("Find Item");
        findItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findItemActionPerformed(evt);
            }
        });
        jMenu1.add(findItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(returnItemWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(findItemWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(borrowItemWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(returnItemWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(findItemWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(borrowItemWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(2824, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findByValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findByValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findByValActionPerformed

    private void cbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTypeActionPerformed

    private void returnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnItemActionPerformed
        closeAllWindows();
        returnItemWindow.setVisible(true);
    }//GEN-LAST:event_returnItemActionPerformed

    private void borrowItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowItemActionPerformed
        closeAllWindows();
        borrowItemWindow.setVisible(true);
    }//GEN-LAST:event_borrowItemActionPerformed

    private void findItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findItemActionPerformed
       closeAllWindows();
       findItemWindow.setVisible(true);
    }//GEN-LAST:event_findItemActionPerformed

    private void itemCodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCodeTxtActionPerformed

    private void borrowItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowItemBtnActionPerformed
        if(validBorrowInput()) {
        String itemCode = itemCodeTxt.getText();
        String memberId = memberIdTxt.getText();
        String borrowDate = ((JTextField)borrowDateTxt.getDateEditor().getUiComponent()).getText();
        LibraryMember libMember = userService.findById(memberId);
        if(libMember == null) {
             JOptionPane.showMessageDialog(null, "Member  not found");
        } else {
                 
        ItemTransaction borrowItem = new ItemTransaction();
        borrowItem.setItemId(itemCode);
        borrowItem.setMemberId(memberId);
        borrowItem.setBorrowDate(borrowDate);
        Item item = itemService.findItemById(borrowItem.getItemId());
       
        String result = "";
        
    

        if(item != null) {
             borrowItem.setItemType(item.getItemType());
        } else {
             JOptionPane.showMessageDialog(null, "Item Id not found");
        }
        if(item.getNoOfCopiesToBorrow() > 0) {
           result = borrowItemService.borrowItem(borrowItem);
        } else {
         result = "Item not avaliable";
        }
        
        if( result == "Item Borrowed successfully") {
            itemService.updateNoOfCopies(itemCode,false);
            transactionService.addTransaction(new Transaction(TransactionType.BORROW));
        }
         JOptionPane.showMessageDialog(null, result);
            resetInputFields();
        }
        }
        else 
        {
         JOptionPane.showMessageDialog(null, "Enter valid input");
        }
         
    }//GEN-LAST:event_borrowItemBtnActionPerformed

    private void returnItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnItemBtnActionPerformed
         if(validReturnInput()) {
        String itemCode = rItemCodeTxt.getText();
        String memberId = rMemberIdTxt.getText();
        String returnDate = ((JTextField)returnDateTxt.getDateEditor().getUiComponent()).getText();
        
        ItemTransaction borrowItem = new ItemTransaction();
        borrowItem.setItemId(itemCode);
        borrowItem.setMemberId(memberId);
        borrowItem.setReturnDate(returnDate);
        String result = borrowItemService.calculateFineAndReturnItem(borrowItem);
        
        if ( result != null) {
            if(result.contains("Fine Applied and returned")) {
              transactionService.addTransaction(new Transaction(TransactionType.FINE));
            }
              itemService.updateNoOfCopies(itemCode,true);
              transactionService.addTransaction(new Transaction(TransactionType.RETURN));
              JOptionPane.showMessageDialog(null, result);
        } else {
              JOptionPane.showMessageDialog(null, "Member did not buy this item");
        }
        resetInputFields();
      }
         else {
             JOptionPane.showMessageDialog(null, "Enter valid input");
         }
    }//GEN-LAST:event_returnItemBtnActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(!findByVal.getText().isEmpty()) {
        String selectedFindByType = String.valueOf(findByType.getSelectedItem());
        
        //get the value from the textbox 
        String selectedValue = findByVal.getText();
        
        if(selectedFindByType == "Title") {
        //get item by title
              Item item = itemService.findItemByTitle(selectedValue);
          if(item == null ) {
              JOptionPane.showMessageDialog(null, "No items found for title");
          } else {
          txtAuthor.setText(item.getAuthor());
          txtPublisher.setText(item.getPublisher());
          txtTitle.setText(item.getTitle());
          txtId.setText(item.getCode());
          txtIsbn.setText(item.getIsbn());
          txtDate.setText(item.getPublishedDate());
          txtAvailable.setText(Integer.toString(item.getNoOfCopiesToBorrow()));
          txtCurrent.setText(Integer.toString(item.getNoOfCopiesCurrentlyBorrowed()));
          cbType.setSelectedItem(item.getRentType().toString());
          cbLan.setSelectedItem(item.getLanguage().toString());
          }
         
        } 
        else {    
          Item item =  itemService.findItemById(selectedValue);
           if(item == null ) {
              JOptionPane.showMessageDialog(null, "No items found for Id");
          } else {
          txtAuthor.setText(item.getAuthor());
          txtPublisher.setText(item.getPublisher());
          txtTitle.setText(item.getTitle());
          txtId.setText(item.getCode());
          txtIsbn.setText(item.getIsbn());
          txtDate.setText(item.getPublishedDate());
          txtAvailable.setText(Integer.toString(item.getNoOfCopiesToBorrow()));
          txtCurrent.setText(Integer.toString(item.getNoOfCopiesCurrentlyBorrowed()));
          cbType.setSelectedItem(item.getRentType().toString());
          cbLan.setSelectedItem(item.getLanguage().toString());    
           }
        }
        
        transactionService.addTransaction(new Transaction(TransactionType.FIND));
       }  
       else {
             JOptionPane.showMessageDialog(null, "Enter valid input");
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void txtPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPublisherActionPerformed

    private void cbLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLanActionPerformed
private void closeAllWindows(){
     returnItemWindow.setVisible(false);
     borrowItemWindow.setVisible(false);
     findItemWindow.setVisible(false);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser borrowDateTxt;
    private javax.swing.JMenuItem borrowItem;
    private javax.swing.JButton borrowItemBtn;
    private javax.swing.JInternalFrame borrowItemWindow;
    private javax.swing.JComboBox<String> cbLan;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JComboBox<String> findByType;
    private javax.swing.JTextField findByVal;
    private javax.swing.JMenuItem findItem;
    private javax.swing.JInternalFrame findItemWindow;
    private javax.swing.JTextField itemCodeTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jTitle;
    private javax.swing.JLabel lFindBy;
    private javax.swing.JTextField memberIdTxt;
    private javax.swing.JTextField rItemCodeTxt;
    private javax.swing.JTextField rMemberIdTxt;
    private com.toedter.calendar.JDateChooser returnDateTxt;
    private javax.swing.JMenuItem returnItem;
    private javax.swing.JButton returnItemBtn;
    private javax.swing.JInternalFrame returnItemWindow;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtAvailable;
    private javax.swing.JTextField txtCurrent;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtPublisher;
    private javax.swing.JTextField txtTitle;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private boolean validReturnInput() {
        if(rItemCodeTxt.getText().isEmpty() || rMemberIdTxt.getText().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }    
    
     private boolean validBorrowInput() {
        if(itemCodeTxt.getText().isEmpty() || memberIdTxt.getText().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }
     
     
    private void resetInputFields()  {
    rItemCodeTxt.setText("");
    rMemberIdTxt.setText("");
    itemCodeTxt.setText("");
    memberIdTxt.setText("");
    }
}

